name: Code Scanning - Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Runs weekly

jobs:
  code-scanning:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.16.3'

    - name: Initialize the CodeQL tools
      uses: github/codeql-action/init@v2
      with:
        languages: go

    - name: Build project
      run: go build ./...

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
